name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package app
        run: |
          mkdir build
          cp -r * build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: build/
